# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf554695e7c4d2e7ef6aacc7b3b45802045b339e7e20140df4b89453c26ca32a62a1ed7fc8d74d95cd071c13315351c855e9254f398e2dea208ab8e1e94ba1a8

test:
  secret_key_base: 763b10d325f748986f07192c307ca58e45136b6617f0d1c85cd2d9da55e93774e8b60595d49aaead343b8376afefb462b231f5a93e3231521c8350bcb931c27b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
